# Generated by Django 2.2.11 on 2020-04-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='user_id',
        ),
    ]
